CREATE TABLE "user"
(
    ID       SERIAL PRIMARY KEY,
    USERNAME VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
    ROLE     TEXT        NOT NULL,
    BALANCE  NUMERIC DEFAULT 0 CHECK ( BALANCE >= 0 )
);

CREATE TABLE location
(
    ID          SERIAL PRIMARY KEY,
    TITLE       VARCHAR(256) NOT NULL,
    DESCRIPTION TEXT
);

CREATE TABLE trainer
(
    ID      SERIAL PRIMARY KEY,
    ORIGIN  VARCHAR(2)  NOT NULL,
    IS_MALE BOOLEAN     NOT NULL,
    NAME    VARCHAR(32) NOT NULL,
    AGE     INTEGER DEFAULT 0 CHECK ( AGE >= 0 )
);

CREATE TABLE pokemon
(
    ID             SERIAL PRIMARY KEY,
    HP             INTEGER DEFAULT 0 CHECK ( HP >= 0 ),
    ATTACK         INTEGER DEFAULT 0 CHECK ( ATTACK >= 0 ),
    PREVIOUS_STAGE INTEGER REFERENCES pokemon (ID),
    TRAINER_ID     INTEGER REFERENCES trainer ON DELETE CASCADE,
    DEFENSE        INTEGER DEFAULT 0 CHECK ( DEFENSE >= 0 ),
    SPEED          INTEGER DEFAULT 0 CHECK ( SPEED >= 0 ),
    NAME           VARCHAR(32)
);

CREATE TABLE fight
(
    ID                 SERIAL PRIMARY KEY,
    FIRST_POKEMON_ID   INTEGER REFERENCES pokemon,
    SECOND_POKEMON_ID  INTEGER REFERENCES pokemon,
    LOCATION_ID        INTEGER REFERENCES location,
    COEFFICIENT        NUMERIC NOT NULL,
    COEFFICIENT_SECOND NUMERIC NOT NULL,
    IS_COMPLETED       BOOLEAN NOT NULL DEFAULT false,
    FIRST_WON          BOOLEAN,
    USER_ID            INTEGER REFERENCES "user" ON DELETE CASCADE
);

CREATE TABLE bet
(
    ID       SERIAL PRIMARY KEY,
    USER_ID  INTEGER REFERENCES "user",
    FIGHT_ID INTEGER REFERENCES fight,
    CREDITS  INTEGER DEFAULT 0 CHECK ( CREDITS >= 0 ),
    CHOICE   BOOLEAN,
    COEF     NUMERIC NOT NULL,
    INCOME   NUMERIC
);

CREATE TABLE pokemon_type
(
    ID   SERIAL PRIMARY KEY,
    TYPE VARCHAR(32) NOT NULL
);

CREATE TABLE has_type
(
    TYPE_ID    INTEGER REFERENCES pokemon_type,
    POKEMON_ID INTEGER REFERENCES pokemon,
    PRIMARY KEY (TYPE_ID, POKEMON_ID)
);

CREATE TABLE location_type
(
    TYPE_ID     INTEGER PRIMARY KEY REFERENCES pokemon_type,
    LOCATION_ID INTEGER REFERENCES location
);

CREATE TABLE abilities
(
    ID             SERIAL PRIMARY KEY,
    TITLE          VARCHAR(32) NOT NULL,
    DESCRIPTION    TEXT        NOT NULL,
    EFFECT_HP      INTEGER DEFAULT 0,
    EFFECT_ATTACK  INTEGER DEFAULT 0,
    EFFECT_DEFENCE INTEGER DEFAULT 0,
    EFFECT_SPEED   INTEGER DEFAULT 0
);

CREATE TABLE has_ability
(
    POKEMON_ID INTEGER REFERENCES pokemon,
    ABILITY_ID INTEGER REFERENCES abilities,
    PRIMARY KEY (POKEMON_ID, ABILITY_ID)
);